function(patchy_assert_qt_free_dependency_tree boundary_target)
  get_property(boundary_visited GLOBAL PROPERTY PATCHY_QT_FREE_BOUNDARY_VISITED)
  if(boundary_target IN_LIST boundary_visited)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY PATCHY_QT_FREE_BOUNDARY_VISITED
               ${boundary_target})
  foreach(link_property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(boundary_links ${boundary_target} ${link_property})
    if(boundary_links)
      foreach(boundary_link IN LISTS boundary_links)
        if(boundary_link MATCHES "Qt[0-9]*::")
          message(FATAL_ERROR
            "Qt-free engine boundary violated: ${boundary_target} ${link_property} contains ${boundary_link}")
        endif()
        if(TARGET ${boundary_link})
          patchy_assert_qt_free_dependency_tree(${boundary_link})
        endif()
      endforeach()
    endif()
  endforeach()
endfunction()
